services:
  redis:
    image: redis
    restart: on-failure
    expose:
      - 6379
    env_file: 
      - ".env"

  db:
    image: postgres
    restart: on-failure
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    env_file: 
      - ".env"

  app:
    build: .
    tty: true
    # command: fastapi run src/main.py --workers 4 --host 0.0.0.0 --port 8000
    command: fastapi dev src/main.py --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: 
      - ".env"
    depends_on:
      db:
        condition: service_healthy
        restart: true

  # celery:
  #   build: .
  #   tty: true
  #   command: celery -A config worker -B -l INFO
  #   restart: on-failure
  #   volumes:
  #     - .:/app
  #   depends_on:
  #     - redis
  #     - db
  #     - app
  #   env_file: 
  #     - ".env"

volumes:
  pg_data: